# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BabyLink' do

pod 'SDWebImage', '~> 3.7.3'
pod 'AFNetworking', '~> 2.6.1'
pod 'MJRefresh', '~> 2.4.12'
pod 'SVProgressHUD', '~> 1.1.3'
end

target 'BabyLinkTests' do

end

target 'BabyLinkUITests' do

end

